version: '3.8'

services:
  postgres:
    container_name: bd_gastos_pessoais
    image: postgres:14.16-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_BANCO_DADOS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: